Java sdk
ovh/pulumi-ovh pull request #170
Opened 2024-05-26 12:02 UTC by philippart-s

@scraly need to talk with you if it's the right way to update and add Java SDK to the provider 😉

2024-06-18 16:00 UTC, philippart-s commented
@scraly th files to check:
 - Makefile
 - build.gradle
 - settings.gradle

All other files are unmodified after auto generation.

Next steps : 
 - add the code and do a first integration?
 - need examples?
 - need docs?
 - ...?

2024-07-25 10:05 UTC, scraly commented
Thanks for working on it 💪.
To have a fully PR we need to have a Makefile that will generate the Java SDK without any manual modifications.

`build.gradle`and `settings.gradle` files can't be modified manually so a tips can be to edit them "automatically" in the Makefile in the `build_java` target.

Like this in the Makefile (at the end of the `build_java` target):

```
build_java: xxxxxx --out sdk/java --build gradle-nexus
        [...]
	echo "patch_java: update gradle info" && \
		cd ./sdk/java/ && \
		sed -i.bak -e 's/JavaLanguageVersion.of(11)/JavaLanguageVersion.of(21)/g' build.gradle && mv build.gradle.bak build.gradle
```

The same things can be applied for `settings.gradle` file also.

2024-07-25 13:00 UTC, scraly requested changes

2024-07-25 13:00 UTC, scraly commented on Makefile
>  VERSION         := $(shell pulumictl get version)
```suggestion
VERSION         := $(shell pulumictl get version)
JAVA_GROUP_ID    := com.${ORG}.pulumi
JAVA_ARTIFACT_ID := ${ORG}
```

2024-07-25 13:05 UTC, scraly commented
When we will succesfully publish the Java package through the GH action, then we can add examples.
To do that I created an issue: #185  

We'll can also create an example in Java in [kubernetes](https://github.com/ovh/pulumi-ovh/tree/main/examples/kubernetes) folder.

2024-08-07 09:17 UTC, scraly commented on Makefile
> +JAVA_GEN_VERSION := v0.12.0
```suggestion
JAVA_GEN_VERSION := v0.13.0
```

2024-08-12 09:44 UTC, philippart-s commented
waouh, thanks for this exhaustive review 😊.
I'll check all your remarks and update the PR, just for the Java version: I'll check in the Pulumi's java generator if are using Java 11 or 21. I think it's better to follow their version.

Again thanks a lot.

2024-08-28 12:52 UTC, scraly approved these changes

2024-08-28 12:53 UTC, merged